version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - database
  database:
    image: "postgres:14-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD="password"
